[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts']
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
# Ignore size limit warnings for EntryPoint (reference implementation exceeds 24KB limit)
ignored_error_codes = [5574]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
